### ISSUE TITLE
删除 elegantbookdown 里的定理定义环境

### ISSUE THREAD

**Issue by fyemath** [hongtaoh/hongtaoh.github.io#1]
在 [ElegantBookdown](https://github.com/XiangyunHuang/ElegantBookdown) 下的提问中 [theorem-block 必须要保留一个？](https://github.com/XiangyunHuang/ElegantBookdown/issues/18) ，， @hongtaoh 提到你有类似的疑问。

造出删除定理环境会出错的原因是，在 .Rprofile 里面有一段对数学环境进行修改的代码，该段代码假定了数学环境会被bookdown激活。你可以直接把那一段删除了就好。

详情请参见 https://github.com/XiangyunHuang/ElegantBookdown/issues/18#issuecomment-804270165

**Comment by hongtaoh** [comment]
超级感谢！谢谢你还专门跑过来跟我说一声！
