### ISSUE TITLE
链接过长

### ISSUE THREAD

**Issue by CyrusYip** [hongtaoh/hongtaoh.github.io#180]
用手机访问 https://hongtaoh.com/cn/2024/09/09/create-py-module/ ，链接显示不全。

![Screenshot_20240923_091757](https://github.com/user-attachments/assets/ab2de820-f185-4179-a50d-5605d89cf7a9)

---

可以用 `overflow-wrap: break-word;` 解决。

https://github.com/CyrusYip/hugo-theme-yue/blob/3893c45b565858c39ace13a289f4225b0afe0124/assets/sass/_style.scss#L11-L22

**Comment by hongtaoh** [comment]
超级感谢！

**Comment by hongtaoh** [comment]
已修改：https://github.com/hongtaoh/hongtaoh.github.io/commit/dcdf9238e7480c55a4123dc8e6a1ba812536a3cc

**Comment by hongtaoh** [comment]
感谢🙏

**Comment by CyrusYip** [comment]
不需要添加到 `@media only screen and (max-width: 600px)`，因为前面添加的是全局生效的。

https://github.com/hongtaoh/hongtaoh.github.io/blob/dcdf9238e7480c55a4123dc8e6a1ba812536a3cc/themes/hugo-ht/static/css/style.css#L430-L432
