### ISSUE TITLE
内容显示不全

### ISSUE THREAD

**Issue by CyrusYip** [hongtaoh/hongtaoh.github.io#184]
用手机浏览 <https://hongtaoh.com/cn/2024/10/11/join/>，最后的表格显示不全。

![Screenshot_20241016_155359](https://github.com/user-attachments/assets/39e85e3a-6836-41dd-9f35-42892536d231)

删掉 `overflow: hidden;` 就能解决问题。

https://github.com/hongtaoh/hongtaoh.github.io/blob/c5669d6f984f30974ab869a76ba18e4e50b4eac6/themes/hugo-ht/static/css/style.css#L179-L181

这里的 `position: relative;` 似乎也可以删掉，还有下面两处：

- https://github.com/hongtaoh/hongtaoh.github.io/blob/c5669d6f984f30974ab869a76ba18e4e50b4eac6/themes/hugo-ht/static/css/style.css#L1-L5
- https://github.com/hongtaoh/hongtaoh.github.io/blob/c5669d6f984f30974ab869a76ba18e4e50b4eac6/themes/hugo-ht/static/css/style.css#L184-L186

**Comment by hongtaoh** [comment]
已解决，十分感谢！
