### ISSUE TITLE
`最后一次修改于`应用于所有文章而非单篇文章

### ISSUE THREAD

**Issue by Shitao5** [hongtaoh/hongtaoh.github.io#44]
遇到的情境是这样的：俺在考古鸿涛 2021 年的中文博客，然后发现文章的标签下写了 `最后一次修改于 2022-11-26`，我想这么凑巧你刚修改的文章被我发现了。而后我又考古了几篇，发现每篇都写着 `最后一次修改于 2022-11-26`。

我想这个信息和在博客首页最下面的 `Site last updated on 2022-11-26` 以及英文博客里的 `Last modified on 2022-11-26` 是一致的。我觉得首页的 `Site last updated on 2022-11-26` 非常合理，不过每篇文章也都有这个信息，会让我觉得“哇！有更新，我来瞧瞧改了啥”。

按照我朴素的直观认识，每篇文章的 `最后一次修改于` 指的是这篇文章最后一次被修改的时间。

**Comment by hongtaoh** [comment]
这个确实是我的问题。我也意识到了这个问题，但是一时半会儿解决不了。目测原因是我用的 github actions。所以呢，每篇文章底下的最后编辑时间都是最近的。好在我的本地保留了准确的信息，以后如果不用 github actions 了就没有这个问题了～

**Comment by Shitao5** [comment]
今天尝试给自己的博客也添加「最后修改于」这样的功能，也遇到了所有文章时间一样的问题，最后参照这篇文章（<https://makewithhugo.com/add-a-last-edited-date/>）里 The Git way 那一节的内容解决了，方法是在 `config.toml` 文件里添加：

```toml
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
```

贴在这里，看看是否可以有帮助😀

**Comment by hongtaoh** [comment]
@Shitao5 试了一次，无法解决问题。这个问题的根本在于我用的是 github actions。换成 netlify 或者 vercel 就可以了，但是我目前还不想换～谢谢你！

**Comment by yihui** [comment]
看你过了这么久还没弄明白问题的症结所在，就举手帮你修了算了（#53）。

**Comment by hongtaoh** [comment]
@yihui 哇噻，看到益辉帮我，我开心了老半天，哈哈哈。超级感谢！一直没去管这个，但能解决心里放松不少。
